### ISSUE TITLE
Failed to create session: No child processes

### ISSUE THREAD

**Issue by Shatur95** [neutrinolabs/xrdp#1677]
Hi! First of all thanks for your work on xrdp!

# Description

I have an issue with connection on Arch Linux - I see black screen with cursor for several minutes and then I see the following message:
![изображение](https://user-images.githubusercontent.com/22453358/92218917-80214c80-eea2-11ea-87a5-6b0cfcd1ae96.png)

I use KRDC as a client, xrdp 0.9.13.1 as a server.

`systemctl status xrdp-sesman.service` shows the following:

```
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: (4383)(139859034752832)[INFO ] calling auth_start_session from pid 4383
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: pam_unix(xrdp-sesman:session): session opened for user gena(uid=1000) by (uid=0)
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: pam_systemd(xrdp-sesman:session): Failed to create session: No child processes
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: pam_env(xrdp-sesman:session): Unrecognized Option: 
                                                   - ignoring line
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: (4383)(139859034752832)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4383]: (4383)(139859034752832)[DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
сен 04 11:50:52 AcerAspire5 xrdp-sesman[4385]: (4385)(139859034752832)[INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf -noreset -nolisten tcp -logfile .xorgxrdp.%s.log
```

# Configuration

It almost default, except path to the Xorg (the path is correct).

<details>
  <summary>xrdp.ini</summary>

```ini
[Globals]
; xrdp.ini file version number
ini_version=1

; fork a new process for each incoming connection
fork=true

; ports to listen on, number alone means listen on all interfaces
; 0.0.0.0 or :: if ipv6 is configured
; space between multiple occurrences
;
; Examples:
;   port=3389
;   port=unix://./tmp/xrdp.socket
;   port=tcp://.:3389                           127.0.0.1:3389
;   port=tcp://:3389                            *:3389
;   port=tcp://<any ipv4 format addr>:3389      192.168.1.1:3389
;   port=tcp6://.:3389                          ::1:3389
;   port=tcp6://:3389                           *:3389
;   port=tcp6://{<any ipv6 format addr>}:3389   {FC00:0:0:0:0:0:0:1}:3389
;   port=vsock://<cid>:<port>
port=3389

; 'port' above should be connected to with vsock instead of tcp
; use this only with number alone in port above
; prefer use vsock://<cid>:<port> above
use_vsock=false

; regulate if the listening socket use socket option tcp_nodelay
; no buffering will be performed in the TCP stack
tcp_nodelay=true

; regulate if the listening socket use socket option keepalive
; if the network connection disappear without close messages the connection will be closed
tcp_keepalive=true

; set tcp send/recv buffer (for experts)
#tcp_send_buffer_bytes=32768
#tcp_recv_buffer_bytes=32768

; security layer can be 'tls', 'rdp' or 'negotiate'
; for client compatible layer
security_layer=negotiate

; minimum security level allowed for client for classic RDP encryption
; use tls_ciphers to configure TLS encryption
; can be 'none', 'low', 'medium', 'high', 'fips'
crypt_level=high

; X.509 certificate and private key
; openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
certificate=
key_file=

; set SSL protocols
; can be comma separated list of 'SSLv3', 'TLSv1', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'
ssl_protocols=TLSv1.2, TLSv1.3
; set TLS cipher suites
#tls_ciphers=HIGH

; Section name to use for automatic login if the client sends username
; and password. If empty, the domain name sent by the client is used.
; If empty and no domain name is given, the first suitable section in
; this file will be used.
autorun=

allow_channels=true
allow_multimon=true
bitmap_cache=true
bitmap_compression=true
bulk_compression=true
#hidelogwindow=true
max_bpp=32
new_cursors=true
; fastpath - can be 'input', 'output', 'both', 'none'
use_fastpath=both
; when true, userid/password *must* be passed on cmd line
#require_credentials=true
; You can set the PAM error text in a gateway setup (MAX 256 chars)
#pamerrortxt=change your password according to policy at http://url

;
; colors used by windows in RGB format
;
blue=009cb5
grey=dedede
#black=000000
#dark_grey=808080
#blue=08246b
#dark_blue=08246b
#white=ffffff
#red=ff0000
#green=00ff00
#background=626c72

;
; configure login screen
;

; Login Screen Window Title
#ls_title=My Login Title

; top level window background color in RGB format
ls_top_window_bg_color=009cb5

; width and height of login screen
ls_width=350
ls_height=430

; login screen background color in RGB format
ls_bg_color=dedede

; optional background image filename (bmp format).
#ls_background_image=

; logo
; full path to bmp-file or file in shared folder
ls_logo_filename=
ls_logo_x_pos=55
ls_logo_y_pos=50

; for positioning labels such as username, password etc
ls_label_x_pos=30
ls_label_width=65

; for positioning text and combo boxes next to above labels
ls_input_x_pos=110
ls_input_width=210

; y pos for first label and combo box
ls_input_y_pos=220

; OK button
ls_btn_ok_x_pos=142
ls_btn_ok_y_pos=370
ls_btn_ok_width=85
ls_btn_ok_height=30

; Cancel button
ls_btn_cancel_x_pos=237
ls_btn_cancel_y_pos=370
ls_btn_cancel_width=85
ls_btn_cancel_height=30

[Logging]
LogFile=xrdp.log
LogLevel=DEBUG
EnableSyslog=true
SyslogLevel=DEBUG
; LogLevel and SysLogLevel could by any of: core, error, warning, info or debug

[Channels]
; Channel names not listed here will be blocked by XRDP.
; You can block any channel by setting its value to false.
; IMPORTANT! All channels are not supported in all use
; cases even if you set all values to true.
; You can override these settings on each session type
; These settings are only used if allow_channels=true
rdpdr=true
rdpsnd=true
drdynvc=true
cliprdr=true
rail=true
xrdpvr=true
tcutils=true

; for debugging xrdp, in section xrdp1, change port=-1 to this:
#port=/tmp/.xrdp/xrdp_display_10

; for debugging xrdp, add following line to section xrdp1
#chansrvport=/tmp/.xrdp/xrdp_chansrv_socket_7210


;
; Session types
;

; Some session types such as Xorg, X11rdp and Xvnc start a display server.
; Startup command-line parameters for the display server are configured
; in sesman.ini. See and configure also sesman.ini.
[Xorg]
name=Xorg
lib=libxup.so
username=ask
password=ask
ip=127.0.0.1
port=-1
code=20

[Xvnc]
name=Xvnc
lib=libvnc.so
username=ask
password=ask
ip=127.0.0.1
port=-1
#xserverbpp=24
#delay_ms=2000

[vnc-any]
name=vnc-any
lib=libvnc.so
ip=ask
port=ask5900
username=na
password=ask
#pamusername=asksame
#pampassword=asksame
#pamsessionmng=127.0.0.1
#delay_ms=2000

[neutrinordp-any]
name=neutrinordp-any
lib=libxrdpneutrinordp.so
ip=ask
port=ask3389
username=ask
password=ask

; You can override the common channel settings for each session type
#channel.rdpdr=true
#channel.rdpsnd=true
#channel.drdynvc=true
#channel.cliprdr=true
#channel.rail=true
#channel.xrdpvr=true
```

</details>

<details>
  <summary>sesman.ini</summary>

```ini
;; See `man 5 sesman.ini` for details

[Globals]
ListenAddress=127.0.0.1
ListenPort=3350
EnableUserWindowManager=true
; Give in relative path to user's home directory
UserWindowManager=startwm.sh
; Give in full path or relative path to /etc/xrdp
DefaultWindowManager=startwm.sh
; Give in full path or relative path to /etc/xrdp
ReconnectScript=reconnectwm.sh

[Security]
AllowRootLogin=true
MaxLoginRetry=4
TerminalServerUsers=tsusers
TerminalServerAdmins=tsadmins
; When AlwaysGroupCheck=false access will be permitted
; if the group TerminalServerUsers is not defined.
AlwaysGroupCheck=false
; When RestrictOutboundClipboard=true clipboard from the
; server is not pushed to the client.
RestrictOutboundClipboard=false

[Sessions]
;; X11DisplayOffset - x11 display number offset
; Type: integer
; Default: 10
X11DisplayOffset=10

;; MaxSessions - maximum number of connections to an xrdp server
; Type: integer
; Default: 0
MaxSessions=50

;; KillDisconnected - kill disconnected sessions
; Type: boolean
; Default: false
; if 1, true, or yes, kill session after 60 seconds
KillDisconnected=false

;; DisconnectedTimeLimit - when to kill idle sessions
; Type: integer
; Default: 0
; if not zero, the seconds before a disconnected session is killed
; min 60 seconds
DisconnectedTimeLimit=0

;; IdleTimeLimit (specify in second) - wait before disconnect idle sessions
; Type: integer
; Default: 0
; Set to 0 to disable idle disconnection.
IdleTimeLimit=0

;; Policy - session allocation policy
; Type: enum [ "Default" | "UBD" | "UBI" | "UBC" | "UBDI" | "UBDC" ]
; Default: Xrdp:<User,BitPerPixel> and Xvnc:<User,BitPerPixel,DisplaySize>
; "UBD" session per <User,BitPerPixel,DisplaySize>
; "UBI" session per <User,BitPerPixel,IPAddr>
; "UBC" session per <User,BitPerPixel,Connection>
; "UBDI" session per <User,BitPerPixel,DisplaySize,IPAddr>
; "UBDC" session per <User,BitPerPixel,DisplaySize,Connection>
Policy=Default

[Logging]
LogFile=xrdp-sesman.log
LogLevel=DEBUG
EnableSyslog=1
SyslogLevel=DEBUG

;
; Session definitions - startup command-line parameters for each session type
;

[Xorg]
; Specify the path of non-suid Xorg executable. It might differ depending
; on your distribution and version. The typical path is shown as follows:
;
; Fedora 26 or later    :  param=/usr/libexec/Xorg
; Debian 9 or later     :  param=/usr/lib/xorg/Xorg
; Ubuntu 16.04 or later :  param=/usr/lib/xorg/Xorg
; Arch Linux            :  param=/usr/lib/xorg-server/Xorg
; CentOS 7              :  param=/usr/bin/Xorg or param=Xorg
;
param=Xorg
; Leave the rest paramaters as-is unless you understand what will happen.
param=-config
param=xrdp/xorg.conf
param=-noreset
param=-nolisten
param=tcp
param=-logfile
param=.xorgxrdp.%s.log

[Xvnc]
param=Xvnc
param=-bs
param=-nolisten
param=tcp
param=-localhost
param=-dpi
param=96

[Chansrv]
; drive redirection, defaults to xrdp_client if not set
FuseMountName=thinclient_drives
; this value allows only the user to acess their own mapped drives.
; Make this more permissive (e.g. 022) if required.
FileUmask=077

[SessionVariables]
PULSE_SCRIPT=/etc/xrdp/pulse/default.pa
```

</details>

**Comment by matt335672** [comment]
"No child processes" suggests you're running out of free process slots.

While the login is happening, try a `ps -ef` or run `top` to see whether you've unintentionally caused a fork bomb somewhere.

**Comment by Shatur95** [comment]
Thanks for the quick response!

> While the login is happening, try a ps -ef or run top to see whether you've unintentionally caused a fork bomb somewhere.

I tied to connect to 127.0.0.1 now and watch for the launched processes but I do not see a lot of running processes, just get this error instantly... Can I provide more logs somehow?

**Comment by matt335672** [comment]
You won't get more out of sesman itself but you can try a `sudo journalctl -S -5m` to get the system logs for the last five minutes. That might give you more clues.

**Comment by Shatur95** [comment]
Thanks for the tip. Here is the log for the last minute. Could you look into it?

<details>
  <summary>sudo journalctl -S -1m</summary>

```
сен 04 14:25:19 AcerAspire5 kwin_x11[582]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 30003, resource id: 125>
сен 04 14:25:19 AcerAspire5 systemd[519]: Started apps-org.kde.konsole-5ff1520dbd314ad88397b4f36d4bf77a.scope.
сен 04 14:25:19 AcerAspire5 plasmashell[645]: file:///usr/lib/qt/qml/QtQuick/Controls/Styles/Plasma/BusyIndicatorStyle.qml:39:9: Q>
сен 04 14:25:19 AcerAspire5 plasmashell[645]: file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:2>
сен 04 14:25:19 AcerAspire5 plasmashell[645]: file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:2>
сен 04 14:25:23 AcerAspire5 krdc[9327]: QWidgetWindow(0x55dbfd991dc0, name="QWidgetClassWindow") must be a top level window.
сен 04 14:25:23 AcerAspire5 plasmashell[645]: file:///usr/share/plasma/plasmoids/org.kde.plasma.taskmanager/contents/ui/Task.qml:2>
сен 04 14:25:39 AcerAspire5 xrdp[1440]: (1440)(139975512209792)[INFO ] Socket 12: AF_INET connection received from 127.0.0.1 port >
сен 04 14:25:39 AcerAspire5 xrdp[1440]: (1440)(139975512209792)[DEBUG] Closed socket 12 (AF_INET 127.0.0.1:3389)
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] Closed socket 11 (AF_INET 0.0.0.0:3389)
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] Using default X.509 certificate: /etc/xrdp/cert.pem
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] Using default X.509 key file: /etc/xrdp/key.pem
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] TLSv1.3 enabled
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] TLSv1.2 enabled
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] Security layer: requested 3, selected 1
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] connected client computer name: AcerAspire5
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] adding channel item name rdpdr chan_id 1004 flags 0xc0800>
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] adding channel item name rdpsnd chan_id 1005 flags 0xc000>
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] adding channel item name cliprdr chan_id 1006 flags 0xc0a>
сен 04 14:25:39 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] TLS connection established from 127.0.0.1 port 37510: TLS>
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] xrdp_0000291f_wm_login_mode_event_00000001
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] Loading keymap file /etc/xrdp/km-00000409.ini
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[WARN ] local keymap file for 0x00000409 found and doesn't match >
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] xrdp_wm_log_msg: connecting to sesman ip 127.0.0.1 port 3>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[INFO ] A connection received from 127.0.0.1 port 40044
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] xrdp_wm_log_msg: sesman connect ok
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] xrdp_wm_log_msg: sending login info to session manager, p>
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] return value from xrdp_mm_connect 0
сен 04 14:25:40 AcerAspire5 audit[1438]: USER_AUTH pid=1438 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:authentication granto>
сен 04 14:25:40 AcerAspire5 kernel: audit: type=1100 audit(1599218740.168:99): pid=1438 uid=0 auid=4294967295 ses=4294967295 msg='>
сен 04 14:25:40 AcerAspire5 dbus-daemon[424]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org>
сен 04 14:25:40 AcerAspire5 dbus-daemon[424]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service'>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: pam_systemd_home(xrdp-sesman:account): systemd-homed is not available: Unit dbus-or>
сен 04 14:25:40 AcerAspire5 audit[1438]: USER_ACCT pid=1438 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=p>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[INFO ] ++ created session (access granted): username gena, >
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[INFO ] starting Xorg session...
сен 04 14:25:40 AcerAspire5 kernel: audit: type=1101 audit(1599218740.171:100): pid=1438 uid=0 auid=4294967295 ses=4294967295 msg=>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[DEBUG] Closed socket 14 (AF_INET 0.0.0.0:5910)
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[DEBUG] Closed socket 14 (AF_INET 0.0.0.0:6010)
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[DEBUG] Closed socket 14 (AF_INET 0.0.0.0:6210)
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[INFO ] xrdp_wm_log_msg: login successful for display 10
сен 04 14:25:40 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[INFO ] calling auth_start_session from pid 10534
сен 04 14:25:40 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] xrdp_wm_log_msg: started connecting
сен 04 14:25:40 AcerAspire5 audit[10534]: CRED_ACQ pid=10534 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam>
сен 04 14:25:40 AcerAspire5 kernel: audit: type=1103 audit(1599218740.185:101): pid=10534 uid=0 auid=4294967295 ses=4294967295 msg>
сен 04 14:25:40 AcerAspire5 kernel: audit: type=1006 audit(1599218740.188:102): pid=10534 uid=0 old-auid=4294967295 auid=1000 tty=>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: pam_unix(xrdp-sesman:session): session opened for user gena(uid=1000) by (uid=0)
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: pam_systemd(xrdp-sesman:session): Failed to create session: No child processes
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: pam_env(xrdp-sesman:session): Unrecognized Option: 
                                                    - ignoring line
сен 04 14:25:40 AcerAspire5 audit[10534]: USER_START pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:session_open grantors=pam_loginui>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] Closed socket 7 (AF_INET 127.0.0.1:3350)
сен 04 14:25:40 AcerAspire5 kernel: audit: type=1105 audit(1599218740.188:103): pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:sessio>
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] Closed socket 8 (AF_INET 127.0.0.1:3350)
сен 04 14:25:40 AcerAspire5 xrdp-sesman[10536]: (10536)(140317158815552)[INFO ] Xorg :10 -auth .Xauthority -config xrdp/xorg.conf >
сен 04 14:25:43 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] Closed socket 19 (AF_UNIX)
сен 04 14:25:47 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] Closed socket 19 (AF_UNIX)
сен 04 14:25:49 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[ERROR] X server for display 10 startup timeout
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[CORE ] waiting for window manager (pid 10535) to exit
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10535]: (10535)(140317158815552)[ERROR] X server for display 10 startup timeout
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10535]: (10535)(140317158815552)[ERROR] another Xserver might already be active on display>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10535]: (10535)(140317158815552)[DEBUG] aborting connection...
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[CORE ] window manager (pid 10535) did exit, cleaning up s>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[INFO ] calling auth_stop_session and auth_end from pid 10>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: pam_unix(xrdp-sesman:session): session closed for user gena
сен 04 14:25:50 AcerAspire5 audit[10534]: USER_END pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:session_close grantors=pam_loginuid>
сен 04 14:25:50 AcerAspire5 audit[10534]: CRED_DISP pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:setcred grantors=pam_shells,pam_fa>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] cleanup_sockets:
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1106 audit(1599218750.221:104): pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:sessio>
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1104 audit(1599218750.221:105): pid=10534 uid=0 auid=1000 ses=7 msg='op=PAM:setcre>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdp_chansrv_>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] cleanup_sockets: deleting /tmp/.xrdp/xrdpapi_10
сен 04 14:25:50 AcerAspire5 xrdp-sesman[10534]: (10534)(140317158815552)[DEBUG] cleanup_sockets: failed to delete /tmp/.xrdp/xrdpa>
сен 04 14:25:50 AcerAspire5 xrdp-sesman[1438]: (1438)(140317158815552)[INFO ] ++ terminated session:  username gena, display :10.0>
сен 04 14:25:50 AcerAspire5 audit[10577]: USER_AUTH pid=10577 uid=1000 auid=1000 ses=1 msg='op=PAM:authentication grantors=pam_fai>
сен 04 14:25:50 AcerAspire5 dbus-daemon[424]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org>
сен 04 14:25:50 AcerAspire5 dbus-daemon[424]: [system] Activation via systemd failed for unit 'dbus-org.freedesktop.home1.service'>
сен 04 14:25:50 AcerAspire5 sudo[10577]: pam_systemd_home(sudo:account): systemd-homed is not available: Unit dbus-org.freedesktop>
сен 04 14:25:50 AcerAspire5 audit[10577]: USER_ACCT pid=10577 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_permit,>
сен 04 14:25:50 AcerAspire5 audit[10577]: CRED_REFR pid=10577 uid=0 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_faillock,pam_>
сен 04 14:25:50 AcerAspire5 audit[10577]: USER_START pid=10577 uid=0 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_limits,>
сен 04 14:25:50 AcerAspire5 sudo[10577]:     gena : TTY=pts/1 ; PWD=/home/gena ; USER=root ; COMMAND=/usr/bin/journalctl -S -1m
сен 04 14:25:50 AcerAspire5 sudo[10577]: pam_unix(sudo:session): session opened for user root(uid=0) by gena(uid=0)
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1100 audit(1599218750.635:106): pid=10577 uid=1000 auid=1000 ses=1 msg='op=PAM:aut>
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1101 audit(1599218750.635:107): pid=10577 uid=1000 auid=1000 ses=1 msg='op=PAM:acc>
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1110 audit(1599218750.635:108): pid=10577 uid=0 auid=1000 ses=1 msg='op=PAM:setcre>
сен 04 14:25:50 AcerAspire5 kernel: audit: type=1105 audit(1599218750.635:109): pid=10577 uid=0 auid=1000 ses=1 msg='op=PAM:sessio>
сен 04 14:25:50 AcerAspire5 xrdp[10527]: (10527)(139975512209792)[DEBUG] Closed socket 19 (AF_UNIX)
```
</details>

**Comment by Shatur95** [comment]
I found that my `.xorgxrdp.10.log` contains the following line:

```
[   650.965] (EE) systemd-logind: failed to get session: PID 2734 does not belong to any known session
```

I tried to set `allowed_users=anybody` in `/etc/X11/Xwrapper.config` but it did not help.

**Comment by usul0184** [comment]
gersilex on the Arch Linux forums at https://bbs.archlinux.org/viewtopic.php?id=258716 figured out this is due to a PAM configuration file issue on Arch Linux.  The current version of pambase 20200721.1-2 has a problematic `/etc/pam.d/system-auth`:

```
#%PAM-1.0

auth       required                    pam_faillock.so      preauth
# Optionally use requisite above if you do not want to prompt for the password
# on locked accounts.
auth       [success=2 default=ignore]  pam_unix.so          try_first_pass nullok
-auth      [success=1 default=ignore]  pam_systemd_home.so
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
auth       required                    pam_env.so
auth       required                    pam_faillock.so      authsucc
# If you drop the above call to pam_faillock.so the lock will be done also
# on non-consecutive authentication failures.

-account   [success=1 default=ignore]  pam_systemd_home.so
account    required                    pam_unix.so
account    optional                    pam_permit.so
account    required                    pam_time.so

-password  [success=1 default=ignore]  pam_systemd_home.so
password   required                    pam_unix.so          try_first_pass nullok shadow
password   optional                    pam_permit.so

session    required                    pam_limits.so
session    required                    pam_unix.so
session    optional                    pam_permit.so
```

The older pambase 20190105.1-2 works with `/etc/pam.d/system-auth` as:

```
#%PAM-1.0

auth      required  pam_unix.so     try_first_pass nullok
auth      optional  pam_permit.so
auth      required  pam_env.so

account   required  pam_unix.so
account   optional  pam_permit.so
account   required  pam_time.so

password  required  pam_unix.so     try_first_pass nullok sha512 shadow
password  optional  pam_permit.so

session   required  pam_limits.so
session   required  pam_unix.so
session   optional  pam_permit.so
```

I don't know PAM well enough to identify the actual problem, though.

**Comment by sanvyruz** [comment]
I have this line too in .xorgxrdp.10.log, but this is possibly non-fatal since I'm able to login to my desktop session:
```
[169739.918] (EE) systemd-logind: failed to get session: PID 5648 does not belong to any known session
```

**Comment by Shatur95** [comment]
Yes, the problem was in another error:

```
[ 1061.599] (EE) parse_vt_settings: Cannot open /dev/tty0 (Permission denied)
```

I fixed it by the following solution: https://github.com/neutrinolabs/xrdp/issues/1554#issuecomment-674868428

**Comment by usul0184** [comment]
@Shatur95, are you able to start, say, gparted without having to `sudo` from a terminal?  If not, you may still have a problem.  @sanvyruz, I suspect you have the same problem.  A user session isn't being created.

**Comment by Shatur95** [comment]
> are you able to start, say, gparted without having to sudo from a terminal? If not, you may still have a problem. 

It asks me for password automatically.
Xrdp works for me, the main problem was in layout.

**Comment by sanvyruz** [comment]
> I suspect you have the same problem. A user session isn't being created.

Xrdp sessions are probably managed by xrdp-sesman. You can list them (I think?) as follows:
```
xrdp-sesadmin -u=sandeep -c=list
password:
[20200907-14:36:48] [DEBUG] libscp initialized
[20200907-14:36:48] [INFO ] [v1c_mng:411] connection ok
Session ID: 870
        Session type: 3
        Screen size: 1600x866, color depth 24
        Idle time: 0 day(s) 0 hour(s) 0 minute(s)
        Connected: 2020/09/07 14:13
[20200907-14:36:48] [DEBUG] Closed socket 4 (AF_INET 127.0.0.1:40216)
```

**Comment by caiwan** [comment]
I have the same exact problem setting up XRDP and accessing from Windows 10. @Shatur95 Care to share what was your solution?

**Comment by Shatur** [comment]
@caiwan, I mentioned the solution in the message above.
