### ISSUE TITLE
meta key alone does not start launcher in KDE

### ISSUE THREAD

**Issue by miklcct** [neutrinolabs/xrdp#2859]
### xrdp version

0.9.21.1

### Detailed xrdp version, build options

~~~
xrdp 0.9.21.1
  A Remote Desktop Protocol Server.
  Copyright (C) 2004-2020 Jay Sorg, Neutrino Labs, and all contributors.
  See https://github.com/neutrinolabs/xrdp for more information.

  Configure options:
      --enable-ipv6
      --enable-jpeg
      --enable-fuse
      --enable-rfxcodec
      --enable-opus
      --enable-painter
      --enable-vsock
      --build=x86_64-linux-gnu
      --prefix=/usr
      --includedir=${prefix}/include
      --mandir=${prefix}/share/man
      --infodir=${prefix}/share/info
      --sysconfdir=/etc
      --localstatedir=/var
      --disable-silent-rules
      --libdir=${prefix}/lib/x86_64-linux-gnu
      --libexecdir=${prefix}/lib/x86_64-linux-gnu
      --disable-maintainer-mode
      --disable-dependency-tracking
      --with-socketdir=/run/xrdp/sockdir
      build_alias=x86_64-linux-gnu
      CFLAGS=-g -O2 -ffile-prefix-map=/build/xrdp-QTF2mN/xrdp-0.9.21.1=. -fstack-protector-strong -Wformat -Werror=format-security
      LDFLAGS=-Wl,-z,relro -Wl,-z,now -Wl,--as-needed
      CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2
      PKG_CONFIG_PATH=/build/xrdp-QTF2mN/xrdp-0.9.21.1/pkgconfig

  Compiled with OpenSSL 3.0.11 19 Sep 2023
~~~

### Operating system & version

Debian 12

### Installation method

dnf / apt / zypper / pkg / etc

### Which backend do you use?

xorgxrdp

### What desktop environment do you use?

KDE

### Environment xrdp running on

VPS on SSD Nodes

### What's your client?

mstsc.exe on Windows 11

### Area(s) with issue?

Keyboard / Mouse

### Steps to reproduce

1. Configure KDE Plasma session (plasma version >= 5.8) such that it has an application launcher, with a global shortcut assigned.
2. Sign in on the physical machine and start the Plasma session. Press the meta key on the keyboard. It should start the application launcher.
3. Sign out the session on the physical machine.
4. Configure the RDP client to handle special keys on the remote machine. Sign in through RDP to the Xrdp server on the same machine, and start the same Plasma session. 
5. Attempt to press the meta key to start the application launcher.

### ✔️ Expected Behavior

The application launcher shows, in the same way as signing in through the physical console.

### ❌ Actual Behavior

Nothing happens.

### Anything else?

The meta key registers as part of a hotkey combination normally in shortcut settings.

**Comment by matt335672** [comment]
Hi @miklcct 

By the 'meta key' I assume you mean the Windows key?

First thing to check is the client settings 'Apply Windows key combinations':-

![image](https://github.com/neutrinolabs/xrdp/assets/30179339/45bc0b90-614c-460c-80be-bbfaff9c05eb)

I think the default is 'Only when using the full screen'.

If that's not it, run `xev` in the session and see what kind of key events you're getting from the key.

**Comment by miklcct** [comment]
Yes, it is applied in the remote machine. Combinations such as meta+F1 works.

20 Nov 2023 09:12:47 matt335672 ***@***.***>:

**Comment by remcoros** [comment]
Same issue here (on Kubuntu). Using correct RDP settings in windows and I'm fullscreen (ALT+Tab works!)

When login locally, xev gives keycode "133" for the meta key
When login using xrdp, xev gives keycode "115".

When setting the "Activate Application Launcher Widget" shortcut, it does allow me to set the "Meta" key. But it shows gibberish.

This is in ~/.config/kglobalshortcutsrc when adding the meta key as an additional shortcut (logged in using xrdp):

> activate widget 3=ៀ?\tAlt+F1,none,Activate Application Launcher Widget

Maybe this info helps

edit: I did not touch any xrdp keyboard remaps and I'm using a default us keyboard

**Comment by matt335672** [comment]
This should be fixed by #3138

**Comment by andreapx** [comment]
> This should be fixed by #3138

@matt335672 I still have this problem. I've just installed the latest version of Debian and when i connect with RDP the Windows Key doesn't do anything

**Comment by matt335672** [comment]
#3138 is merged into devel, not into xrdp 0.9.x or 0.10.x.

**Comment by andreapx** [comment]
> #3138 is merged into devel, not into xrdp 0.9.x or 0.10.x.

Ops, sorry!
