### ISSUE TITLE
Password hash breaks VNC password auth

### ISSUE THREAD

**Issue by bdm310** [neutrinolabs/xrdp#519]
rfbEncryptBytes now uses a hash of the VNC password in at least devel and noorders. Commit dcdb617e63239763c2896100a59b965a04ce4ebb in devel mentions doing this for Xvnc. It ends up breaking connections to at least vino though, resulting in "VNC password failed" in logs. Simply commenting out the hash generation solves the issue for me. I don't know what else would have this issue or if this is even necessarily an xrdp problem. RFC6143 doesn't mention hashing, however.

**Comment by jsorg71** [comment]
This is fixed in vncpassfile branch, merging soon.

**Comment by metalefty** [comment]
The fix has been merged. I think it's resolved.

**Comment by proski** [comment]
I still get VNC authentication failure on reconnect (not always, but maybe half of the time). This is an important issue, we should try to fix it in 0.9.1.

**Comment by proski** [comment]
I think I know what's happening. We are using the same file for all sessions. But the file contents is not constant anymore. We should have password files per session. I believe the original file should be removed if found, as it's likely to have the user's password.
